config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  post   '/logout',  to: 'sessions#destroy'
  root :to => 'users#show'
  
  resources :homes
  resources :users
  get    '/ajax',   to: 'ajaxs#new'
  post   '/ajax',   to: 'ajaxs#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/canvasobject.rb
class Canvasobject < ApplicationRecord
    belongs_to :user
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :plates
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
end

app/models/linkplatetag.rb
class Linkplatetag < ApplicationRecord
    belongs_to :plate
    belongs_to :tag
end

app/models/plate.rb
class Plate < ApplicationRecord
    belongs_to :user
    belongs_to :group

    validates :text, presence: true
end

app/models/setting.rb
class Setting < ApplicationRecord
    belongs_to :user
end

app/models/tab.rb
class Tab < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :linkplatetags
    has_many :plates, through: :linkplatetags
end

app/models/user.rb
class User < ApplicationRecord
    has_many :plates
    has_many :canvasobjects
    has_one :setting

    validates :name, presence: true, uniqueness:true, length: { maximum: 255 }
    validates :password, presence: true,length: { minimum: 10 },confirmation: true
    validate :add_error_massage

    def add_error_massage
      if name.blank?
        errors.add("ユーザ名を入力して下さい")
      end
    end

    # SessionsControllerにてauthenticateメソッドを使うため
    has_secure_password
end

app/controllers/ajaxs_controller.rb
class AjaxsController < ApplicationController
  def new
  end


  def create

    # ここではパースしません。
    # fabric.jsが、jsonを読み込む際にしてくれるっぽい
    json_hash = request.body.read

    if request.headers[:Accept] == '*/*' then 

      # レイアウト保存処理
      setting = Setting.find_by(user_id: session[:user_id])
      setting.update(classname: json_hash)
    else

      # キャンバス保存処理
      canvsobj = Canvasobject.find_by(user_id: session[:user_id])
      if canvsobj.present? then
        canvsobj.update(canvasobjects_json: json_hash)
      else
        newcanvasobj = Canvasobject.new()
        newcanvasobj.user_id = session[:user_id]
        newcanvasobj.canvasobjects_json = json_hash
        newcanvasobj.save
      end 
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    before_action :user_logged_in?

    def user_logged_in?
      if session[:user_id]
        begin
          @current_user = User.find_by(id: session[:user_id])
        rescue ActiveRecord::RecordNotFound
          reset_user_session
        end
      end
      return if @current_user
      # @current_userが取得できなかった場合はログイン画面にリダイレクト
      flash[:referer] = request.fullpath
      redirect_to user_path
    end
    
    def reset_user_session
      session[:user_id] = nil
      @current_user = nil
    end

    require 'csv'

    def new
        @plates = Plate.includes(:group).where(user_id: session[:user_id])
        respond_to do |format|
            format.csv do
                send_posts_csv(@plates)
            end
        end
    end
    # ＣＳＶ作成＆出力
    def send_posts_csv(plates)
        csv_data = CSV.generate do |csv|
            header = %w(text group created_at updated_at)
            csv << header
    
            plates.each do |plate|
                values = [
                    plate.text,
                    plate.group.name,
                    plate.updated_at,
                    plate.created_at,
                ]
                csv << values
            end 
        end
        send_data(csv_data, filename: "TagPlate.csv")
    end

    def show
        @table   = Plate.new
        @group   = Group.new
        @setting = Setting.find_by(user_id: session[:user_id])
        @tables  = Plate.includes(:group).where(user_id: session[:user_id]).order(created_at: 'DESC')
        @count   = @tables.length
        @object  = Canvasobject.find_by(user_id: session[:user_id])
    end

    def create
        if params[:group].nil? then 
            # プレート登録処理
            table = Plate.new(plates_params)
            table.user_id = session[:user_id]
            table.save!
            
            newplate =  Plate.where(user_id: session[:user_id]).last
            adding   =  Group.select('name').find_by(id: newplate.group_id,user_id: session[:user_id]).name
            newplate = [newplate] + [adding]
            render json: newplate
        else
            # グループ登録処理
            group = Group.new(plates_params)
            group.user_id = session[:user_id]
            group.save!
        end
    end

    private
    def plates_params
        if params[:group].nil? then
            return params.require(:plate).permit(:text,:group_id)
        else
            return params.require(:group).permit(:name)
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def destroy
    # ログアウト
    session[:user_id] = nil
    redirect_to :controller => 'users', :action => 'show'
  end

  def create
    user = User.find_by(name: params[:session][:name])

    if user && user.authenticate(params[:session][:password_digest])
      # ログイン
      session[:user_id] = user.id
      # 初期値追加ゾーン！！！！！
      if user.login_count == 0 then

          groups = ['グループ１','グループ２','グループ３']
          for group in groups
            initgroup         = Group.new()
            initgroup.user_id = user.id
            initgroup.name    = group
            initgroup.save
          end
    
          groupid = Group.select('id').where(user_id: user.id).first

          # 初めてのプレート追加
          firstplate          = Plate.new()
          firstplate.user_id  = user.id
          firstplate.text     = 'TagPlateへのユーザ登録ありがとうございます!さっそくですが、このプレートを右側のキャンバスにドラッグしてみてください。'
          firstplate.group_id = groupid.id
          firstplate.save
    
          settings = Setting.new()
          settings.user_id        = user.id
          settings.classname      = '16 1 1.5 1 250 #008080 #50d2d2'
          settings.usingsnap      = 'false'
          settings.snapdist       = '5px'
          settings.usinggrid      = 'false'
          settings.save

          canvasobjects         = Canvasobject.new()
          canvasobjects.user_id = user.id
          # とりあえずリテラルで(;^ω^)
          canvasobjects.canvasobjects_json = '{"version":"3.3.0","background":"white"}'
          canvasobjects.save
      end

      user.update_attribute(:login_count, user.login_count + 1)

      redirect_to home_url(user)
    else
      # エラーメッセージを作成する
      redirect_to :controller => 'users', :action => 'show',:message => 'ユーザ名もしくはパスワードが違います'
      # render ('users/show')
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def show
        @User = User.new
    end
    
    def create
        @User = User.new(users_params)
        @User.login_count = 0
        if @User.save then
            # ログインさせましょう
            render 'show'
        else    
            # エラーメッセージ表示
            render 'show'
        end
    end

    private
    def users_params
        params.require(:user).permit(:name,:password,:password_confirmation)
    end
end

app/helpers/ajaxs_helper.rb
module AjaxsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/show.html.slim
- content_for(:title, "TagPlate")
div#app 
  header#header
  div#leftside
    nav#leftsidenavi
      div#leftsidenavi-wrapper
        a#aAllPlates class='active' title='プレート'
          = image_tag 'AllPlates.png',   :size => "40x40"
          = image_tag 'AllPlatesWH.png', :size => "40x40" 
        a#aAddPlates title='プレート追加'
          = image_tag 'AddPlates.png',   :size => "40x40"
          = image_tag 'AddPlatesWH.png', :size => "40x40"
        a#aEditGroup title='グループ追加'
          = image_tag 'Group.png',       :size => "40x40"
          = image_tag 'GroupWH.png',     :size => "40x40"
        a#aText title='テキスト挿入'
          = image_tag 'Text.png',        :size => "40x40"
          = image_tag 'TextWH.png',      :size => "40x40"
        a#aShape title='図形挿入'
          = image_tag 'Shape.png',       :size => "40x40"
          = image_tag 'ShapeWH.png',     :size => "40x40"
        a#aEditTags title='フリーライン'
          = image_tag 'FreeLine.png',    :size => "40x40"
          = image_tag 'FreeLineWH.png',  :size => "40x40"
    div#toolbar 
      div#AllPlates.tabcontents
        p.platescount = @count
        div#content-wrapper  
          -@tables.each do |table|
            div.content-detail.whitebkcol03 title='右方向へドラッグ＆ドロップ' data=  {:update    => table.updated_at.in_time_zone('Tokyo'),
                                                                                    :create     => table.created_at.in_time_zone('Tokyo'),
                                                                                    :groupname  => table.group.name,}
              div.front.fsize13 draggable="true" = table.text         
              nav.updateddate = table.updated_at.in_time_zone('Tokyo')
              nav.groupname = table.group.name
      div#AddPlates.tabcontents
        div#edittop
          = form_for(@table,url:homes_path, method: :post,remote: :true) do |f| 
            p テキスト
            = f.text_area :text,:placeholder=>'テキストを入力(140文字まで入力可能)',:maxlength=>'140'
            p 関連付けるグループ 
            = f.select :group_id, options_from_collection_for_select(Group.where(user_id: session[:user_id]),:id, :name) 
            = f.submit '追加',:class=>'submit'
          end
      div#EditGroup.tabcontents
          = form_for(@group,url:homes_path, method: :post,remote: :true) do |f| 
            p グループ名
            = f.text_field :name,:placeholder=>'グループ名を入力',:maxlength=>'20'
            = f.submit '追加',:class=>'submit'
          end
      div#Text.tabcontents
        div.texts.fsize16 draggable="true" style = 'font-family:"Meiryo";' テキストを入力（メイリオ）
        div.texts.fsize16 draggable="true" style = 'font-family:"Meiryo UI";' テキストを入力（Meiryo UI）
        div.texts.fsize16 draggable="true" style = 'font-family:"Yu Gothic";' テキストを入力（游ゴシック）
        div.texts.fsize16 draggable="true" style = 'font-family:"Yu Mincho";' テキストを入力（游明朝体）
        div.texts.fsize16 draggable="true" style = 'font-family:"Yu Gothic UI";' テキストを入力（Yu Gothic UI）
        div.texts.fsize16 draggable="true" style = 'font-family:"ＭＳ ゴシック";' テキストを入力（ＭＳゴシック）
        div.texts.fsize16 draggable="true" style = 'font-family:"ＭＳ Ｐゴシック";' テキストを入力（ＭＳ Ｐゴシック）
        div.texts.fsize16 draggable="true" style = 'font-family:"MS UI Gothic";' テキストを入力（MS UI Gothic）
        div.texts.fsize16 draggable="true" style = 'font-family:"ＭＳ 明朝";' テキストを入力（ＭＳ 明朝）
        div.texts.fsize16 draggable="true" style = 'font-family:"ＭＳ Ｐ明朝";' テキストを入力（ＭＳ Ｐ明朝）

      div#Shape.tabcontents style = 'overflow:scroll;'
        div#images
          -for num in 1..300 do
            div.imageshape
              img.lazyload data-src= "/assets/(#{num}).png" width = '40px' 
      div#FreeLine.tabcontents
        input#drawtoggle type="button" value="お絵描きモードＯＮ"
        div#drawmenu 
          p 線の種類
          select#drawmode 
            option value="Pencil" ペンシル
            option value="Circle" サークル
            option value="Spray" スプレー
            option value="Pattern" パターン
          p 線の幅：0
          input#linewidth type="range" value='0' min= '0' max='150'
          p 線の色
          input#linecolor type = 'color'
          p 影の幅：0
          input#lineshadow type="range" value='0' min= '0' max='50'
          p 影のズレ幅：0
          input#offsetshadow type="range" value='0' min= '0' max='50'          
          p 影の色
          input#shadowcolor type = 'color'          
  div#main.whitebkcol03
    div#mainlogo-wrapper
      div#logo TagPlate
    div#operation
      div#operation-icons 
        div#save-canvas 
          = image_tag 'Save.png',  :size => "30x30" ,:id=>'practice'
          p 保存
        div#redo-canvas 
          = image_tag 'Redo.png',  :size => "30x30"
          p 元に戻す
        div#undo-canvas 
          = image_tag 'Undo.png',  :size => "30x30"
          p やりなおす
        div#align-elements 
          = image_tag 'Align.png',  :size => "30x30"
          p 整列       
        div#copy-elements 
          = image_tag 'Copy.png',  :size => "30x30"
          p コピー
        div#remove-elements 
          = image_tag 'Remove.png',:size => "30x30"
          p 削除
      div#alignmenu style = 'display:none;'
        ul
          li#left.fsize20 左揃え
          #alignleft   = image_tag 'alignleft.png',  :size => "30x30"
          li#top.fsize20 上揃え
          #aligntop    = image_tag 'aligntop.png',   :size => "30x30"
          li#right.fsize20 右揃え
          #alignright  = image_tag 'alignright.png', :size => "30x30"
          li#bottom.fsize20 下揃え
          #alignbottom = image_tag 'alignbottom.png',:size => "30x30"
    canvas#thecanvas 
  div#rightside
    div#rightnavi
      nav#rightsidenavi
        div#rightsidenavi-wrapper
          div#setting.modalsetting
            = image_tag 'Setting.png',:size => "40x40", :title=>'設定'
            p スタイル<br>設定
          div#settingwindow style = 'display:none;'
            div.fsize30 プレートスタイル設定
            div#settingwrapper
              div#fullscaleview
                //クラス格納順[fontsize(0)、textalign(1)、lineheight(2)、fontstyle(3) 、width(4)、color(5)、background(6)]（7）
                div#previewmodel class = @setting.classname  この文章はサンプルです。行間、フォントサイズ、フォントスタイルなどの変更が可能です。
                div#attention.fsize12 ※最大幅を指定可能ですが、フォントサイズにより変動します。今後修正していきます。
                div#slidebarwidth
              div#fontcolor.fsize20 フォントカラー選択：
              input#font type = 'color'
              div#backgroundcolor.fsize20　バックカラー選択：
              input#background type = 'color'
              div#textcentering
                p センタリング
                div#slidebar1
                div#slidebar1scale.fsize15 左　　　　　　　　　　　　中央　　　　　　　　　　　　右
              div#lineheightselecting
                p テキスト行間
                div#slidebar2
                div#slidebar2scale.fsize15 １　　　　１．５　　　　２　　　　 ２．５　　　　 ３
              div#fontsizing
                p フォントサイズ
                div#slidebar3
                div#slidebar3scale.fsize15 １　　　　　　　　　　　　　２　　　　　　　　　　　　　３
              div#fontstyling
                p フォントスタイル
                div#slidebar4
                div#slidebar4scale.fsize15 Ｎ　　　　　　　　Ｂ　　　　　　　　Ｉ　　　　　　　　Ｕ
          div#help.modalhelp  
            = image_tag 'Help.png',   :size => "40x40", :title=>'ヘルプ'
            p ヘルプ
          div#helpwindow style = 'display:none;'
            div#helptitle.fsize30 TagPlate とは？
            div.helptext.fsize20 140文字以内で自分だけのメモ書きを作成することができます。
            div.helptext.fsize20 作成したメモは、中央のキャンバスへ付箋のように張り付けることが可能です。
            div.helptext.fsize20 張り付けた付箋は編集することができます。
            div.helptext.fsize20 キャンバスにて編集された内容は、そのまま保存することができます。
            div.helptext.fsize20 次回ログイン時には、前回終了した状態から作業を再開することが可能です。
            div.helptext.fsize20 キャンバスの現在の状態を、PDF形式で出力することができます。
            div.helptext.fsize20 加えて、保存されているメモ書きはCSV形式で出力が可能です。
            div.helptext.fsize20 いくつかの画像も用意しましたので、付箋とともに張り付けてみてください。
          div#logout.modallogout
            = image_tag 'Logout.png',  :size => "40x40", :title=>'ログイン'
            p ログアウト
          div#logoutwindow style = 'display:none;'
            div#logouttitle.fsize30 ログアウト処理を行います。
            div#questionsave.fsize20 ・・・の前に、キャンバス編集内容の保存はお済みでしょうか？
            div#savetologout.fsize25 保存してからログアウト
            div#dologout.fsize25 いますぐにログアウト
          div#import 
            = image_tag 'CSVImport.png',:size => "40x40", :title=>'CSVインポート'
            p インポート
          div#export 
            = link_to '', new_home_path(format: :csv), id:'anchorexport'
            = image_tag 'CSVExport.png',:size => "40x40", :title=>'CSVエクスポート'
            p エクスポート
          div#pdfexport 
            = image_tag 'PDFExport.png',:size => "40x40", :title=>'PDFエクスポート'
            p PDF出力 
      div#platesinformation
        p#texttitle.fsize15  テキスト
        p#text.fsize15.whitebkcol03
        p#grouptitle.fsize15  グループ
        p#group.fsize15.whitebkcol03
        p#updatedtitle.fsize15  更新日時
        p#updated.fsize15.whitebkcol03
        p#createdtitle.fsize15  作成日時
        p#created.fsize15.whitebkcol03
      div#tabnavi
        p ＜☆お絵描きモードの注意点☆＞</br>お絵描きモードで描画した内容を、</br>大量にコピーすることはやめましょう。</br>メモリ不足が発生し、ブラウザがクラッシュしてしまいます。</br>当アプリ「TagPlate」の挙動もおかしくなりますので、大量コピーはやめましょう。
        p ＜文字や画像が不鮮明になった＞</br>キャンバスを保存していただいた後に、</br>ページをリロードしていただくと、文字が鮮明に表示され、見やすくなります。</br>また、ブラウザの拡大率は、100％でご使用いただくことをお勧めいたします。
footer#footer
  //作業用の要素をここに置いてます
  div#canvasjson data= {:canvasjson => @object.canvasobjects_json}
  canvas#work

app/views/layouts/_error_massages.html.slim
-if @table.errors.any?
  div#error_explanation
    ul
      -@table.errors.full_massages.each do |massage|
        li = massage

app/views/layouts/application.html.slim
doctype html
html
  head
    title = yield :title 
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    script type = 'text/javascript' src='https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js'
    script type = 'text/javascript' src='https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js'
    script type = 'text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.min.js'
    script type = 'text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/fabric.js/3.3.2/fabric.js'
    script type = 'text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/Modaal/0.4.4/js/modaal.js'
    script type = 'text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/js/select2.min.js'
    script type = 'text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/jquery.perfect-scrollbar/1.4.0/perfect-scrollbar.js'
    script type = 'text/javascript' src="https://cdn.jsdelivr.net/npm/lazyload@2.0.0-rc.2/lazyload.js"
    link rel='stylesheet' type='text/css' href='https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/css/select2.min.css'
    link rel='stylesheet' type='text/css' href='https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css'
    link rel='stylesheet' type='text/css' href='https://cdnjs.cloudflare.com/ajax/libs/Modaal/0.4.4/css/modaal.css'
    link rel='stylesheet' type='text/css' href='https://cdnjs.cloudflare.com/ajax/libs/jquery.perfect-scrollbar/1.4.0/css/perfect-scrollbar.min.css'
    = javascript_include_tag 'html2canvas.js'
    body
    = yield

app/views/users/show.html.slim
- content_for(:title, "TagPlate ログイン")
div#app
  div#loginmain
    div#logowrapper
      div#titlelogo TagPlate
    div#wrapper
      div#filltop
      div#loginsection
        div#inputlogin
          h1.algin1.fsize30 ログイン
          = form_for(:session,url:login_path) do |f| 
            = f.label :name, 'ユーザ名' 
            = f.text_field :name 
            = f.label :password_digest, 'パスワード' 
            = f.password_field :password_digest
            = f.submit 'ログイン'
          end
          div#questionlogin.algin1.fsize14　ユーザー登録画面を表示

        div#inputcreate.nonactive
          h1.mainfcol01.algin1.fsize30 ユーザ登録
          = form_for(@User) do |f| 
            = f.label :name, 'ユーザ名' 
            = f.text_field :name 
            = f.label :password, 'パスワード(10文字以上ご入力願います)' 
            = f.password_field :password
            = f.label :password_confirmation, 'パスワード（確認のため再度ご入力願います）' 
            = f.password_field :password_confirmation
            = f.submit 'ユーザ登録'
          end
          div#questioncreate.algin1.fsize14　ログイン画面を表示